# Generated by Django 4.0.1 on 2023-10-18 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='имя категории')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug категории')),
                ('image', models.ImageField(default=None, upload_to='images/category', verbose_name='изображение категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug продукта')),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
                ('image', models.ImageField(default=None, upload_to='images/product/', verbose_name='изображение продукта')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='images/product/preview', verbose_name='изображение продукта (превью)')),
                ('thumb_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/product/thumb', verbose_name='изображение продукта (миниатюра)')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug подкатегории')),
                ('image', models.ImageField(default=None, upload_to='images/subcategory', verbose_name='изображение подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='products.category')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_products', to='products.product', verbose_name='рецепт в списке покупок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopping_items', to=settings.AUTH_USER_MODEL, verbose_name='пользователь списка покупок')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_shopping_list'),
        ),
    ]
